services:
  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
    env_file: ./.env
    ports:
      - "443:443"
    restart: on-failure

  mariadb:
    container_name: mariadb
    hostname: mariadb.srcs_inception
    networks:
      - inception
    build:
      context: ./requirements/mariadb
    env_file: ./.env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"

  wordpress:
    container_name: wordpress
    hostname: wordpress.srcs_inception
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build:
      context: ./requirements/wordpress
    env_file: ./.env
    depends_on:
      - mariadb
    restart: on-failure

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/victofer/data/wordpress"
  mariadb:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/victofer/data/mariadb"

networks:
  inception:
    driver: bridge
