version: "3"
services:
  nginx:
    container_name: "nginx"
    build:
      context: ./requeriments/nginx
      dockerfile: Dockerfile
    ports:
      - 8080:443
    volumes:
      - ./requeriments/nginx/html:/var/www/html
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/victofer/data/mariadb/"
