version: "3"
services:
  mariadb:
    container_name: mariadb
    #hostname: mariadb.srcs_inception
    build: requeriments/mariadb/
    env_file:
      - .env
    networks:
      - webnet
    volumes:
      - "/var/lib/mysql"
    expose:
      - 3306:3306
    restart: always

networks:
  webnet:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/victofer/data/mariadb/"
