version: "3.8"
services:
  nginx:
    container_name: "nginx"
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 8080:443
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - "wordpress:/var/www/wordpress"
    ports:
      - "9000:9000"
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/victofer/data/mariadb/"

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/victofer/data/wordpress/"
