version: "3.8"
services:
  nginx:
    container_name: "nginx"
    build:
      context: ./requeriments/nginx
      dockerfile: Dockerfile
    ports:
      - 8080:443
    volumes:
      - ./requeriments/nginx/html:/var/www/html
    networks:
      - webnet

  mariadb:
    container_name: mariadb
    hostname: mariadb.srcs_inception
    build: requirements/mariadb/
    env_file:
      - .env
    networks:
      - webnet
    volumes:
      - "mariadb:/var/lib/mysql"
    expose:
      - 3306
    restart: always

networks:
  webnet:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/victofer/data/mariadb/"
